---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  hosts: test-kitchen
  ansible_verbose: true
  sudo: true

platforms:
  - name: Ben/sles12
  - name: webhippie/opensuse-13.2

verifier:
  ruby_bindir: '/usr/bin'

suites:
 - name: default
